"""PDF export via reportlab's Platypus layer.

Deliberately NOT canvas.drawString: that cannot wrap text, which forces
manual truncation and silently loses content off the right edge.
"""

from __future__ import annotations

import re
from datetime import datetime
from pathlib import Path

from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.platypus import (
    PageBreak,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)

import config
from utils import store
from utils.helpers import strip_markdown
from utils.logger import get_logger

log = get_logger(__name__)

PRIMARY = colors.HexColor("#0F4C5C")
ACCENT = colors.HexColor("#C98A4B")
LIGHT = colors.HexColor("#F3EFE7")


def _styles():
    base = getSampleStyleSheet()
    return {
        "title": ParagraphStyle(
            "TPTitle", parent=base["Title"], fontSize=22, textColor=PRIMARY,
            spaceAfter=6, alignment=TA_CENTER,
        ),
        "subtitle": ParagraphStyle(
            "TPSubtitle", parent=base["Normal"], fontSize=11, textColor=colors.grey,
            alignment=TA_CENTER, spaceAfter=18,
        ),
        "day": ParagraphStyle(
            "TPDay", parent=base["Heading2"], fontSize=14, textColor=PRIMARY, spaceBefore=14, spaceAfter=2,
        ),
        "weather": ParagraphStyle(
            "TPWeather", parent=base["Normal"], fontSize=9, textColor=ACCENT, spaceAfter=6,
        ),
        "body": ParagraphStyle(
            "TPBody", parent=base["Normal"], fontSize=10, leading=15, spaceAfter=3,
        ),
        "section": ParagraphStyle(
            "TPSection", parent=base["Heading2"], fontSize=13, textColor=PRIMARY, spaceBefore=12, spaceAfter=6,
        ),
    }


def _footer(canvas_obj, doc):
    canvas_obj.saveState()
    canvas_obj.setFont("Helvetica", 8)
    canvas_obj.setFillColor(colors.grey)
    canvas_obj.drawCentredString(A4[0] / 2, 12 * mm, f"Page {doc.page}")
    canvas_obj.drawRightString(
        A4[0] - 18 * mm, 12 * mm, "Generated by AI Travel Planner (India)"
    )
    canvas_obj.restoreState()


def _slug(text: str) -> str:
    return re.sub(r"[^A-Za-z0-9]+", "_", str(text)).strip("_") or "trip"


def _markdown_to_flowables(text: str, styles) -> list:
    """Very small markdown renderer: headings, bullets, paragraphs."""
    flowables = []
    for raw in strip_markdown(text).splitlines():
        line = raw.rstrip()
        if not line.strip():
            flowables.append(Spacer(1, 4))
            continue
        if re.match(r"^Day\s+\d+", line, flags=re.IGNORECASE):
            flowables.append(Paragraph(line, styles["day"]))
        elif line.startswith("- "):
            flowables.append(Paragraph(f"&bull; {line[2:]}", styles["body"]))
        else:
            flowables.append(Paragraph(line, styles["body"]))
    return flowables


def build_pdf(itinerary: dict | None = None, budget: dict | None = None,
              narrative: str = "", filename: str | None = None) -> Path:
    itinerary = itinerary or store.get("itinerary") or {}
    budget = budget or store.get("budget") or {}
    styles = _styles()

    city = itinerary.get("city") or "Your Trip"
    filename = filename or f"{_slug(city)}_itinerary_{datetime.now():%Y%m%d_%H%M%S}.pdf"
    path = config.EXPORT_DIR / filename

    doc = SimpleDocTemplate(
        str(path), pagesize=A4,
        leftMargin=18 * mm, rightMargin=18 * mm,
        topMargin=18 * mm, bottomMargin=20 * mm,
        title=f"Travel Itinerary - {city}",
    )

    flow: list = [Paragraph(f"Travel Itinerary: {city}", styles["title"])]

    meta_bits = []
    if itinerary.get("start_date"):
        meta_bits.append(f"From {itinerary['start_date']}")
    if itinerary.get("days"):
        meta_bits.append(f"{itinerary['days']} days")
    if itinerary.get("travellers"):
        meta_bits.append(f"{itinerary['travellers']} traveller(s)")
    if itinerary.get("style"):
        meta_bits.append(str(itinerary["style"]))
    flow.append(Paragraph(" &nbsp;|&nbsp; ".join(meta_bits) or "Personalised plan", styles["subtitle"]))

    plan = itinerary.get("plan") or []
    if plan:
        flow.append(Paragraph("Day-by-day plan", styles["section"]))
        for day in plan:
            flow.append(Paragraph(f"Day {day.get('day')} &mdash; {day.get('date', '')}", styles["day"]))
            flow.append(Paragraph(str(day.get("weather_summary", "")), styles["weather"]))
            for slot in ("morning", "afternoon", "evening"):
                value = day.get(slot)
                if value:
                    flow.append(Paragraph(f"<b>{slot.title()}:</b> {strip_markdown(str(value))}", styles["body"]))
            if day.get("notes"):
                flow.append(Paragraph(f"<i>{strip_markdown(str(day['notes']))}</i>", styles["body"]))
            cost = day.get("estimated_entry_cost_inr")
            if cost:
                flow.append(Paragraph(f"Estimated entry fees: INR {cost:,}", styles["body"]))
            flow.append(Spacer(1, 6))

    if budget.get("items"):
        flow.append(Spacer(1, 10))
        flow.append(Paragraph("Cost summary", styles["section"]))
        rows = [["Category", "Amount (INR)"]]
        rows += [[k, f"{v:,.0f}"] for k, v in budget["items"].items()]
        rows.append(["Total", f"{budget.get('total', 0):,.0f}"])

        table = Table(rows, colWidths=[95 * mm, 55 * mm], hAlign="LEFT")
        table.setStyle(
            TableStyle(
                [
                    ("BACKGROUND", (0, 0), (-1, 0), PRIMARY),
                    ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                    ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                    ("FONTNAME", (0, -1), (-1, -1), "Helvetica-Bold"),
                    ("BACKGROUND", (0, -1), (-1, -1), LIGHT),
                    ("ROWBACKGROUNDS", (0, 1), (-1, -2), [colors.white, LIGHT]),
                    ("ALIGN", (1, 0), (1, -1), "RIGHT"),
                    ("FONTSIZE", (0, 0), (-1, -1), 10),
                    ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
                    ("TOPPADDING", (0, 0), (-1, -1), 6),
                    ("GRID", (0, 0), (-1, -1), 0.4, colors.HexColor("#D8D2C6")),
                ]
            )
        )
        flow.append(table)
        if budget.get("accommodation_source"):
            flow.append(Spacer(1, 4))
            flow.append(Paragraph(f"<i>Accommodation basis: {budget['accommodation_source']}</i>", styles["body"]))

    if narrative:
        flow.append(PageBreak())
        flow.append(Paragraph("Planner notes", styles["section"]))
        flow.extend(_markdown_to_flowables(narrative, styles))

    if len(flow) <= 2:
        flow.append(Paragraph("No itinerary has been generated yet.", styles["body"]))

    doc.build(flow, onFirstPage=_footer, onLaterPages=_footer)
    return path


def export_itinerary_pdf() -> str:
    """Agent-facing wrapper."""
    try:
        if not store.get("itinerary"):
            return "No itinerary has been built yet. Call build_itinerary first."
        path = build_pdf(narrative=store.get("last_answer", ""))
        store.put("pdf_path", str(path))
        return f"PDF created at {path}. Tell the user it is ready in the Export tab."
    except Exception as exc:
        log.exception("export_itinerary_pdf failed")
        return f"PDF export failed: {exc}"


EXPORT_ITINERARY_PDF_SCHEMA = {
    "name": "export_itinerary_pdf",
    "description": (
        "Render the current itinerary and budget into a formatted PDF file. Call this ONLY "
        "when the user explicitly asks to download, save or export the plan."
    ),
    "parameters": {"type": "object", "properties": {}, "required": []},
}
